Repository bermarte/js-quiz, pull requests merged in 2020-12, with the labels that each got.

#6 questions added
  src/data.js
Labels: data

#4 first code exampla
  .vscode/settings.json
  index.html
  public/style.css
  src/data.js
  src/init/index.js
Labels: enhancement

#8 added carosel for seperate the questions
  index.html
  public/style.css
  src/init/index.js
Labels: enhancement

#10 a little style added to the project
  index.html
  public/style.css
Labels: enhancement

#14 modify review section PR
  src/init/review.js
Labels: js-quiz-g5, question
